"""Render the tutorial directory; optionally sync the same public JSON to the website."""
import argparse,collections,json,pathlib,shutil,re
P=pathlib.Path(__file__).resolve().parents[1]
args=argparse.ArgumentParser();args.add_argument('--website',type=pathlib.Path);args.add_argument('--check',action='store_true');args=args.parse_args()
data=json.loads((P/'data/tutorials.json').read_text(encoding='utf-8'));items=data['items']
assert len(items)==data['stats']['total'] and len({r['id'] for r in items})==len(items)
assert len({r['url'].rstrip('/') for r in items})==len(items)
assert all(r['url'].startswith(('https://','http://')) for r in items)
assert not any(r['language']=='中文' and r['format'] in ['视频','课程与工作坊'] for r in items)
def esc(s):return re.sub(r'([\\|\[\]<>])',r'\\\1',s.replace('\n',' '))
topics=sorted({r['topic'] for r in items});lines=['<!-- Generated by scripts/build-tutorials.py from data/tutorials.json. -->','# 科研教程与文章目录','',f"**{len(items)} 项** · 更新于 {data['updatedAt']} · [网站搜索与筛选](https://skill.createsci.com/tutorials)",'','[返回项目首页](README.md) · [教程征集与计划](TUTORIAL-PLAN.md) · [补充教程](https://github.com/ZMoe2024/awesome-research-skills/issues/new?template=tutorial.yml) · [JSON 数据](data/tutorials.json)','',data['policy'],'','收录不代表已完整阅读、观看或复现。链接访问状态来自整理时的记录，可能发生变化；付费资源只提供原作者入口，不转载全文。','','## 按主题浏览','']
for i,topic in enumerate(topics):lines.append(f'- [{topic}](#topic-{i+1})（{sum(r["topic"]==topic for r in items)}）')
for i,topic in enumerate(topics):
 lines += ['',f'<a id="topic-{i+1}"></a>',f'## {topic}','','| 教程 / 文章 | 作者 | 形式 · 语言 | 访问 |','| --- | --- | --- | --- |']
 for r in [r for r in items if r['topic']==topic]:lines.append(f'| [{esc(r["title"])}]({r["url"]}) | {esc(r["author"])} | {r["format"]} · {r["language"]} | {r["availability"]} |')
text='\n'.join(lines)+'\n';dest=P/'TUTORIALS.md'
if args.check:assert dest.read_text(encoding='utf-8')==text,'Rebuild TUTORIALS.md'
else:dest.write_text(text,encoding='utf-8')
if args.website:
 target=args.website/'lib/tutorial-catalog.json'
 if args.check:assert target.read_bytes()==(P/'data/tutorials.json').read_bytes()
 else:shutil.copyfile(P/'data/tutorials.json',target)
 target=args.website/'public/resources/tutorials.json'
 if args.check:assert target.read_bytes()==(P/'data/tutorials.json').read_bytes()
 else:shutil.copyfile(P/'data/tutorials.json',target)
print(f'PASS: {len(items)} tutorial entries; unique IDs/URLs; language rule; Markdown and website data in sync.')
